objects = {
  { name = "", type = "", x = 130, y = 443, z = 0, width = 9, height = 5 },
  { name = "", type = "SpawnPoint", x = 878, y = 1178, z = 0, width = 1, height = 1, properties = { Professions = "all" } },
  { name = "", type = "SpawnPoint", x = 875, y = 1153, z = 0, width = 1, height = 1, properties = { Professions = "all" } },
  { name = "", type = "SpawnPoint", x = 877, y = 1121, z = 0, width = 1, height = 1, properties = { Professions = "all" } },
  { name = "", type = "SpawnPoint", x = 835, y = 1178, z = 0, width = 1, height = 1, properties = { Professions = "all" } },
  { name = "junkyard", type = "ParkingStall", x = 836, y = 1114, z = 0, width = 9, height = 24, properties = { Direction = "S", FaceDirection = true } },
  { name = "bad", type = "ParkingStall", x = 789, y = 1181, z = 0, width = 3, height = 4 },
  { name = "bad", type = "ParkingStall", x = 778, y = 1183, z = 0, width = 6, height = 3 },
  { name = "bad", type = "ParkingStall", x = 736, y = 1181, z = 0, width = 3, height = 4 },
  { name = "bad", type = "ParkingStall", x = 707, y = 1179, z = 0, width = 3, height = 4 },
  { name = "junkyard", type = "ParkingStall", x = 727, y = 1159, z = 0, width = 4, height = 6 },
  { name = "sport", type = "ParkingStall", x = 868, y = 1182, z = 0, width = 3, height = 4 },
  { name = "junkyard", type = "ParkingStall", x = 735, y = 1113, z = 0, width = 6, height = 12 },
  { name = "good", type = "ParkingStall", x = 745, y = 1139, z = 0, width = 3, height = 4 },
  { name = "fossoil", type = "ParkingStall", x = 827, y = 1181, z = 0, width = 3, height = 4 },
  { name = "fossoil", type = "ParkingStall", x = 836, y = 1189, z = 0, width = 4, height = 3 },
  { name = "fossoil", type = "ParkingStall", x = 825, y = 1169, z = 0, width = 12, height = 4 },
  { name = "fossoil", type = "ParkingStall", x = 811, y = 1177, z = 0, width = 12, height = 6 },
  { name = "fossoil", type = "ParkingStall", x = 842, y = 1150, z = 0, width = 4, height = 6 },
  { name = "junkyard", type = "ParkingStall", x = 758, y = 1125, z = 0, width = 21, height = 16 },
  { name = "good", type = "ParkingStall", x = 771, y = 1115, z = 0, width = 3, height = 4 },
  { name = "good", type = "ParkingStall", x = 764, y = 1114, z = 0, width = 4, height = 6 },
  { name = "trafficjamn", type = "ParkingStall", x = 743, y = 1114, z = 0, width = 12, height = 12 },
  { name = "bad", type = "ParkingStall", x = 820, y = 1130, z = 0, width = 3, height = 4 },
  { name = "", type = "WaterZone", x = -1, y = 1310, z = 0, width = 53, height = 18, properties = { WaterGround = false, WaterShore = true } },
  { name = "", type = "WaterZone", x = 43, y = 1301, z = 0, width = 50, height = 24, properties = { WaterGround = false, WaterShore = true } },
  { name = "", type = "WaterZone", x = 217, y = 1472, z = 0, width = 28, height = 28 },
  { name = "", type = "WaterZone", x = 83, y = 1308, z = 0, width = 40, height = 42 },
  { name = "", type = "WaterZone", x = 109, y = 1335, z = 0, width = 50, height = 48, properties = { WaterGround = false, WaterShore = true } },
  { name = "", type = "WaterZone", x = 144, y = 1368, z = 0, width = 38, height = 41, properties = { WaterGround = false, WaterShore = true } },
  { name = "", type = "WaterZone", x = 169, y = 1399, z = 0, width = 30, height = 32, properties = { WaterGround = false, WaterShore = true } },
  { name = "", type = "WaterZone", x = 181, y = 1415, z = 0, width = 41, height = 44, properties = { WaterGround = false, WaterShore = true } },
  { name = "", type = "WaterZone", x = 203, y = 1448, z = 0, width = 32, height = 27, properties = { WaterGround = false, WaterShore = true } },
  { name = "", type = "WaterFlow", x = 1, y = 1297, z = 0, width = 83, height = 32, properties = { WaterDirection = 90, WaterSpeed = 0.7 } },
  { name = "", type = "WaterFlow", x = 84, y = 1301, z = 0, width = 173, height = 199, properties = { WaterDirection = 180, WaterSpeed = 0.8 } }
}
